version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome123
      POSTGRES_DB: smarthome
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smarthome -d smarthome"]
      interval: 5s
      timeout: 5s
      retries: 5

  temperature-api:
    build:
      context: ./smart_home/temperature-api
    container_name: smarthome-temperature-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=smarthome
      - DB_PASSWORD=smarthome123
      - DB_NAME=smarthome
    networks:
      - smarthome-network

networks:
  smarthome-network:
    driver: bridge

volumes:
  postgres_data: